type: anthropic
params:
  name: claude-3-7-sonnet
  version: claude-3-7-sonnet-20250219

  temperature: 1
  max_response_tokens: 16000
  reasoning_model: true
  max_reasoning_tokens: 48000

  input_price_per_1M_tokens: 3
  output_price_per_1M_tokens: 15
