type: openai
params:
  name: o3
  version: o3-2025-04-16

  temperature: 1
  max_response_tokens: 20000
  reasoning_model: true
  max_reasoning_tokens: 80000

  input_price_per_1M_tokens: 10
  output_price_per_1M_tokens: 40
