type: openai
params:
  name: o4-mini
  version: o4-mini-2025-04-16

  temperature: 1
  max_response_tokens: 20000
  reasoning_model: true
  max_reasoning_tokens: 80000

  input_price_per_1M_tokens: 1.1
  output_price_per_1M_tokens: 4.4
