type: atari_pong_multi
params:
  max_steps_per_player: 2000
  max_observation: false
  skip_frame: 4
  resize_frame: false
  color_reduction: false
  normalize_obs: false
  stack_frame: 4
  sticky_action: 0.25
  noop_start: true
  recording_type: gif
