experiment:
  name: default
  seed: 0
  async_mode: true
  num_episodes: 60
  results_dir: results

environment: kuhn_poker

agents:
  - type: prompt_agent
    params:
      model: gpt-4.1
      visual_obs: true

  - type: cfr_agent
